manage =  "xpath://*[@id='content-wrapper']/div/div[2]/div/div/rd-widget/div/rd-widget-header/div/div/div[2]/a"
company_name  = "xpath://html/body/div/div[2]/div/div[2]/div/div/form/div[2]/input"
type_of_work ="name:type"
amount="name:price"
status="id:selectStatus"
due_date="name:dueDate"
Description="name:comment"
save_btn="id:saveButton"
cancel_btn="xpath:/html/body/div/div[2]/div/div[2]/div/div/form/a[3]/button"
